# default values
all:
  pager:
    homepage_max:        10
    answers_max:         10
    users_max:           10

  feed:
    max: 10
  tag:
    cloud_max:   40
  .global:
    universe:            on
