# default rules
question:
  url:   /question/:stripped_title
  param: { module: question, action: show }
popular_questions: 
  url:   /index/:page 
  param: { module: question, action: list }
login:
  url:   /login 
  param: { module: user, action: login } 
homepage:
  url:   /
  param: { module: question, action: list }
recent_questions:
  url:   /recent/:page
  param: {module: question, action: recent, page: 0 }


default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
