# question
question:
  url:   /question/:stripped_title
  param: { module: question, action: show }

popular_questions:
  url:   /index/:page
  param: { module: question, action: list }

recent_questions:
  url:   /recent
  param: { module: question, action: recent }

add_question:
  url:   /add_question
  param: { module: question, action: add }

# answers
recent_answers:
  url:   /recent/answers
  param: { module: answer, action: recent }

add_answer:
  url:   /add_anwser
  param: { module: answer, action: add }

answers:
  url:   /question/:stripped_title/page/:page
  param: { module: question, action: show, page: 1 }

# user
user_interests:
  url:   /question/:stripped_title/interests/:page
  param: { module: user, action: listInterestedBy }

user_profile:
  url:   /user/:nickname
  param: { module: user, action: show }

current_user_profile:
  url:   /user
  param: { module: user, action: show }

add_account:
  url:   /add_user
  param: { module: user, action: new }

# login
login:
  url:   /login
  param: { module: user, action: login }

logout:
  url:   /logout
  param: { module: user, action: logout }

# default rules
homepage:
  url:   /
  param: { module: question, action: list }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
