<?php
// auto-generated by sfPropelCrud
// date: 2008/02/06 21:35:59
?>
<?php

/**
 * question actions.
 *
 * @package		askeet
 * @subpackage question
 * @author		 Your name here
 * @version		SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class questionActions extends sfActions
{
	public function executeIndex () {
		$this->forward('question', 'list');
	}

	public function executeList ()
	{
		$this->question_pager = QuestionPeer::getHomepagePager(
			$this->getRequestParameter('page', 1) );
	}

	public function executeShow()
	{
	  $this->question = QuestionPeer::getQuestionFromTitle($this->getRequestParameter('stripped_title'));
	 
	  $this->forward404Unless($this->question);
	}

	public function executeRecent()
	{
	  $this->question_pager = QuestionPeer::getRecentPager($this->getRequestParameter('page', 1));
	}

}
